version: "2"

run:
  timeout: 10m
  # Режим загрузки модулей: vendor (если используется vendor каталог) или mod (по умолчанию)
  # modules-download-mode: vendor

# Форматеры - инструменты для автоматического форматирования кода
# Запуск: golangci-lint fmt или make fmt
formatters:
  enable:
    # Форматирование импортов: группировка стандартных, внешних и локальных пакетов
    - goimports
    # Автоматическое разбиение длинных строк
    - golines

    ## Опционально:
    #- gofumpt  # строже gofmt, но обратно совместим
    #- gci      # расширенная группировка импортов

  settings:
    goimports:
      # Локальные пакеты группируются после сторонних
      local-prefixes:
        - github.com/art-injener/satellite-scout

    golines:
      # Максимальная длина строки (по умолчанию 100)
      max-len: 120

# Больше информации https://golangci-lint.run/usage/linters/
linters:
  # Используем "none" и явно включаем нужные линтеры
  default: none

  # Отключаем избыточные или устаревшие линтеры
  disable:
    # wsl/wsl_v5 — слишком строгие правила пустых строк (косметика)
    - wsl
    # nlreturn — пустые строки перед return (косметика)
    - nlreturn
    # mnd — magic number detector слишком агрессивный для орбитальной математики
    - mnd
    # godox — блокирует TODO/FIXME комментарии, полезные для разработки
    - godox
    # gochecknoglobals — sentinel-ошибки как глобальные переменные это идиоматичный Go
    - gochecknoglobals

  enable:
    # ===== КОРРЕКТНОСТЬ / ЛОВЛЯ БАГОВ =====

    # Проверяет исходный код и сообщает о подозрительных конструкциях (Printf, format strings и т.д.)
    - govet
    # Набор правил статического анализа от staticcheck
    - staticcheck
    # Обнаруживает непроверенные ошибки
    - errcheck
    # Проблемы со схемой переноса ошибок (Go 1.13+)
    - errorlint
    # Неиспользуемые константы, переменные, функции и типы
    - unused
    # Неиспользуемые назначения переменным
    - ineffassign
    # Замена golint — расширяемый линтер
    - revive
    # Удаляет ненужные преобразования типов
    - unconvert
    # Обнаруживает дублирование кода
    - dupl
    # Находит повторяющиеся строки, которые могут быть заменены константой
    - goconst
    # Sentinel-ошибки с префиксом Err, типы ошибок с суффиксом Error
    - errname
    # Проверяет правильную обработку ошибок (автофикс)
    - err113
    # Обнаруживает места, где переменные цикла копируются (Go 1.22+)
    - copyloopvar
    # Два временных значения, умноженных вместе (time.Duration * time.Second)
    - durationcheck
    # Исчерпываемость инструкций enum switch
    - exhaustive
    # Объявления срезов с ненулевой начальной длиной
    - makezero
    # Возвращает nil, даже если проверяет что ошибка не nil
    - nilerr
    # Расширенная проверка nil-ошибок (дополняет nilerr)
    - nilnesserr
    # Одновременный возврат nil-ошибки и недопустимого значения
    - nilnil
    # Проверяет pass []any as any в variadic func(...any)
    - asasalint
    # Проверяет наличие тегов в (де)сериализуемых структурах
    - musttag
    # Обнаруживает затенение встроенных идентификаторов Go
    - predeclared
    # Ошибки конструирования URL с хостом и портом через Sprintf
    - nosprintfhostport
    # Консистентность типа ресивера методов
    - recvcheck
    # Валидация директив компилятора (//go:)
    - gocheckcompilerdirectives
    # Проверяет embedded-типы в структурах (в т.ч. запрет embedded mutex)
    - embeddedstructfieldcheck
    # Предотвращает переприсваивание пакетных переменных
    - reassign
    # Предотвращает не-ASCII символы в идентификаторах (защита от случайной кириллицы)
    - asciicheck
    # Проверяет исчерпывающность для "sum types"
    - gochecksumtype
    # Неправильное использование bytes/strings (автофикс)
    - mirror
    # Голые возвраты в функциях
    - nakedret
    # Запрет именованных возвратов (уменьшает когнитивную нагрузку)
    - nonamedreturns
    # Предотвращает загрязнение интерфейсами
    - iface
    # Проверяет смешивание iota с другими значениями в const-блоках
    - iotamixing

    # ===== БЕЗОПАСНОСТЬ =====

    # Проверяет исходный код на проблемы безопасности
    - gosec
    # Опасные unicode-последовательности (троянский источник)
    - bidichk

    # ===== HTTP / СЕТЬ =====

    # Проверяет закрытие тела HTTP-ответа
    - bodyclose
    # Проверяет использование не унаследованного контекста
    - contextcheck
    # HTTP-запросы без context.Context
    - noctx
    # Корректность HTTP-заголовков (canonical headers)
    - canonicalheader

    # ===== SQL (задел на будущее) =====

    # Проверяет закрытие sql.Rows, sql.Stmt
    - sqlclosecheck
    # Проверяет Rows.Err после итерации по результатам SQL
    - rowserrcheck

    # ===== ПРОИЗВОДИТЕЛЬНОСТЬ =====

    # fmt.Sprintf → более быстрые альтернативы (автофикс)
    - perfsprint
    # Бесполезные присваивания
    - wastedassign
    # Integer range в циклах для Go 1.22+ (автофикс)
    - intrange
    # Предаллокация срезов (важно для DSP/обработки IQ-сэмплов)
    - prealloc
    # Неиспользуемые параметры функций
    - unparam

    # ===== СЛОЖНОСТЬ КОДА =====

    # Цикломатическая сложность функций
    - gocyclo
    # Когнитивная сложность функций (дополняет gocyclo)
    - gocognit
    # Длинные функции
    - funlen
    # Глубоко вложенные if-операторы
    - nestif

    # ===== КАЧЕСТВО / СОВРЕМЕННОСТЬ =====

    # Диагностика: баги, производительность, стиль (AST-шаблоны)
    - gocritic
    # Отсутствие функций инициализации
    - gochecknoinits
    # Корректность использования директив nolint
    - nolintlint
    # Возможность использования переменных/констант из стандартной библиотеки
    - usestdlibvars
    # Вложенные контексты в циклах (автофикс)
    - fatcontext
    # Упрощения с использованием современных возможностей Go
    - modernize
    # Функции из golang.org/x/exp/ → стандартные (автофикс)
    - exptostd
    # Использование log/slog на соответствие стилю
    - sloglint
    # Выравнивание тегов структур (автофикс)
    - tagalign

    # ===== ТЕСТЫ =====

    # Проверяет функции из testing-пакета
    - usetesting
    # Проверяет тестируемость примеров (expected output)
    - testableexamples

  # Настройки линтеров
  settings:
    govet:
      # Включить все анализаторы
      enable-all: true
      disable:
        # fieldalignment слишком строгий — заставляет оптимизировать padding структур
        - fieldalignment
      settings:
        shadow:
          # Строгая проверка затенения переменных
          strict: true

    staticcheck:
      # Включить все проверки кроме стилистических
      checks:
        - all
        # Incorrect or missing package comment
        - -ST1000
        # Use consistent method receiver names
        - -ST1016
        # Omit embedded fields from selector expression
        - -QF1008

    errcheck:
      # Отчет о присвоении ошибок пустому идентификатору: `num, _ := strconv.Atoi(numStr)`
      check-blank: true
      # Отчет о непроверенных type assertions: `a := b.(MyStruct)`
      check-type-assertions: true

    depguard:
      rules:
        main:
          # Разрешить все импорты по умолчанию
          allow:
            - $gostd
            - github.com/art-injener/satellite-scout
            - github.com/joshuaferrara/go-satellite
            - github.com/pkg/errors
        deprecated:
          # Запрет устаревших пакетов во всех файлах
          files:
            - "$all"
          deny:
            - pkg: math/rand$
              desc: Use math/rand/v2 instead, see https://go.dev/blog/randv2

    gocyclo:
      # Минимальная цикломатическая сложность. По-умолчанию 30, рекомендуется 10-20
      min-complexity: 20

    gocognit:
      # Минимальная когнитивная сложность. По-умолчанию 30, рекомендуется 10-20
      min-complexity: 20

    cyclop:
      # Максимальная цикломатическая сложность (для TLE парсинга функции могут быть сложными)
      max-complexity: 20

    gosec:
      excludes:
        # Ошибки аудита не проверены
        - G104
        # URL-адрес, предоставленный HTTP-запросу в качестве входных данных для заражения
        - G107
        # Небезопасный источник случайных чисел (rand)
        - G404
        # Неявное наложение псевдонимов в памяти элементов из инструкции range
        - G601

    funlen:
      # Минимальное количество строк функции для срабатывания
      lines: 150
      # Минимальное количество операторов функции для срабатывания
      statements: 80

    nestif:
      # Минимальная сложность операторов if
      min-complexity: 4

    dupl:
      # Минимальное количество дублированных символов (увеличено для матем. кода)
      threshold: 150

    goconst:
      # Искать среди чисел
      numbers: true
      # Минимальное количество вхождений строки для срабатывания
      min-occurrences: 10
      # Минимальное значение повторений для чисел
      min: 3
      # Игнорировать, когда константа не используется в качестве аргумента функции
      ignore-calls: false

    gocritic:
      settings:
        captLocal:
          # Не ограничивать проверку только параметрами
          paramsOnly: false
        underef:
          # Не пропускать (*x).method() для pointer receivers
          skipRecvDeref: false

    nakedret:
      # Запретить naked returns полностью (0 = во всех функциях)
      max-func-lines: 0

    revive:
      rules:
        - name: var-naming
          arguments: [["ID", "UID", "UUID", "URL", "IP", "API", "HTTP", "TLE", "SDR", "SSE", "FSK", "DSP", "IQ"], []]

    nolintlint:
      # Линтеры, для которых не требуется объяснение в nolint
      allow-no-explanation: [funlen, gocognit]
      # Требовать объяснение для директив nolint
      require-explanation: true
      # Требовать указания конкретного линтера в nolint
      require-specific: true

    embeddedstructfieldcheck:
      # Запретить embedded sync.Mutex и sync.RWMutex (безопасность конкурентного кода)
      forbid-mutex: true

    reassign:
      # Проверять все пакетные переменные на переприсваивание
      patterns:
        - ".*"

    sloglint:
      # Запретить смешивание key-value аргументов и атрибутов
      no-mixed-args: true
      # Требовать snake_case для ключей
      key-naming-case: snake
      # Требовать использование контекста (если есть в scope функции)
      context: scope

    tagalign:
      # Выравнивать теги структур
      align: true
      # Сортировать теги
      sort: true

    perfsprint:
      # Проверять все форматы
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      # Не оптимизировать конкатенацию строк (иногда менее читаемо)
      strconcat: false

    usetesting:
      # Обнаруживать использование os.TempDir() вместо t.TempDir()
      os-temp-dir: true

    exhaustive:
      # Проверять switch и map на исчерпываемость
      check:
        - switch
        - map

  # Исключения для линтеров
  exclusions:
    # Предупреждать о неиспользуемых правилах исключений
    warn-unused: true
    # Предустановленные исключения
    presets:
      - std-error-handling
      - common-false-positives
    # Пользовательские исключения
    rules:
      # Исключения для тестовых файлов
      - path: _test\.go
        linters:
          - gosec       # В тестах допустимо менее строгое отношение к безопасности
          - funlen      # Тестовые функции могут быть длинными (table-driven tests)
          - gocyclo     # Сложность в тестах менее критична
          - gocognit    # Когнитивная сложность в тестах менее критична
          - err113      # В тестах допустимо упрощённое создание ошибок
          - errcheck    # В тестах допустимо игнорировать некоторые ошибки
          - goconst     # В тестах допустимы повторяющиеся строки
          - dupl        # В тестах допустимо дублирование (table-driven tests)
          - bodyclose   # В тестах HTTP response body менее критично
          - noctx       # В тестах HTTP-запросы без контекста допустимы

issues:
  # Максимальное количество задач на один линтер. 0 = без ограничений
  max-issues-per-linter: 0
  # Максимальное количество задач с одинаковым текстом. 0 = без ограничений
  max-same-issues: 0
